### ISSUE TITLE
Recommend users to use a certain tag not master

### ISSUE THREAD

**Issue by peaceiris** [ponicode/dogstring-action#10]
This action is currently in the beta version and workflow shows the use case with the master branch. We need to update the example workflow on the README before users start to use this action on their production workflow. When we will release a major version of this action with some breaking changes, the user's workflows suddenly start to fail. Providing the master branch as production-ready of this action is very difficult.

```yaml
- uses: ponicode/dogstring-action@master  # Not recommended
- uses: ponicode/dogstring-action@v1.0.0  # Best
- uses: ponicode/dogstring-action@v1      # Better
```

For continuous upgrading of this action, we can recommend users the Dependabot.

```yaml
# .github/dependabot.yml
version: 2
updates:
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "daily"
  labels:
  - "CI/CD"
  commit-message:
    prefix: ci
```

Also, we can provide a stable tag like `v1`. I prefer this approach with my actions. ([peaceiris/actions-gh-pages/.github/workflows/update-major-tag.yml](https://github.com/peaceiris/actions-gh-pages/blob/4c8cffc919935c69a40648ca19e65bd69f4d5eb3/.github/workflows/update-major-tag.yml))
